import React, { useState } from "react";
import FlowLayout from "../components/FlowLayout";
import { MessagesSquare, Save, Plus } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "../lib/trpc";

export default function MessagesTemplatesPage() {
  const { data: templates, refetch } = trpc.templates.list.useQuery();
  const saveMutation = trpc.templates.save.useMutation();
  const [title, setTitle] = useState("");
  const [template, setTemplate] = useState("");
  const [selectedId, setSelectedId] = useState<number | undefined>();
  const selectTemplate = (item: any) => { setSelectedId(item.id); setTitle(item.title); setTemplate(item.content); };
  const save = async (e: React.FormEvent) => { e.preventDefault(); if (!title.trim() || !template.trim()) return toast.error("Informe um título e o conteúdo."); try { await saveMutation.mutateAsync({ id: selectedId, title, content: template }); await refetch(); toast.success("Template salvo no seu workspace."); } catch (e: any) { toast.error(e.message); } };
  const preview = template || "Digite um template para visualizar aqui.";
  return <FlowLayout activeItem="Mensagens"><div className="max-w-5xl mx-auto space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold tracking-tight text-slate-900">Templates de mensagens</h1><p className="mt-1 text-sm text-slate-500">Crie suas próprias mensagens. O FlowPromos não adiciona modelos automaticamente.</p></div><button onClick={() => { setSelectedId(undefined); setTitle(""); setTemplate(""); }} className="inline-flex items-center gap-2 rounded-xl bg-black px-4 py-2.5 text-xs font-semibold text-white"><Plus className="h-4 w-4" />Novo template</button></div><div className="grid grid-cols-1 md:grid-cols-3 gap-6"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-xs space-y-2"><h2 className="text-sm font-bold">Seus templates</h2>{templates?.length ? templates.map((item: any) => <button key={item.id} onClick={() => selectTemplate(item)} className={`w-full rounded-lg p-3 text-left text-xs ${selectedId === item.id ? "bg-slate-900 text-white" : "bg-slate-50 text-slate-700"}`}>{item.title}</button>) : <p className="text-xs text-slate-400 py-4">Nenhum template criado.</p>}</div><form onSubmit={save} className="md:col-span-2 rounded-2xl border border-slate-200 bg-white p-6 shadow-xs space-y-4"><label className="text-xs font-semibold text-slate-700">Título<input value={title} onChange={e => setTitle(e.target.value)} placeholder="Nome do seu template" className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-xs" /></label><label className="text-xs font-semibold text-slate-700">Mensagem<textarea rows={11} value={template} onChange={e => setTemplate(e.target.value)} placeholder="Escreva sua mensagem usando {titulo}, {preco_final}, {cupom} e {link}" className="mt-1 w-full rounded-xl border border-slate-300 p-3 font-mono text-xs" /></label><p className="text-[11px] text-slate-400">Variáveis: <span className="font-mono">{"{titulo}"}, {"{preco_original}"}, {"{preco_final}"}, {"{desconto}"}, {"{cupom}"}, {"{link}"}</span></p><button disabled={saveMutation.isPending} className="inline-flex items-center gap-2 rounded-xl bg-black px-4 py-2.5 text-xs font-semibold text-white"><Save className="h-4 w-4" />Salvar template</button><div className="rounded-2xl border border-slate-200 bg-[#EFEAE2] p-4"><div className="flex items-center gap-2 text-xs font-bold text-slate-700"><MessagesSquare className="h-4 w-4 text-emerald-600" />Pré-visualização</div><div className="mt-3 rounded-xl bg-white p-3.5 text-xs whitespace-pre-wrap">{preview}</div></div></form></div></div></FlowLayout>;
}
