from pathlib import Path
p=Path('/home/ubuntu/flowpromos/server/routers.ts')
s=p.read_text()
marker='  // Painel Administrativo Geral'
module='''  automation: router({\n    get: protectedProcedure.query(async ({ ctx }) => {\n      const db = await getDb();\n      if (!db) return null;\n      const [job] = await db.select().from(automationJobs).where(eq(automationJobs.userId, ctx.user.id)).limit(1);\n      return job || null;\n    }),\n    enable: protectedProcedure.input(z.object({ cronExpression: z.string().default("0 */15 * * * *") })).mutation(async ({ input, ctx }) => {\n      const db = await getDb();\n      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });\n      const [existing] = await db.select().from(automationJobs).where(eq(automationJobs.userId, ctx.user.id)).limit(1);\n      if (existing?.scheduleCronTaskUid) return { success: true, taskUid: existing.scheduleCronTaskUid };\n      const session = parseCookie(ctx.req.headers.cookie || "")[COOKIE_NAME] || "";\n      const job = await createHeartbeatJob({ name: `flowpromos-scan-${ctx.user.id}`, cron: input.cronExpression, path: "/api/scheduled/scan-promotions", payload: { userId: ctx.user.id }, description: "Varredura periódica de promoções configuradas pelo usuário" }, session);\n      if (existing) await db.update(automationJobs).set({ scheduleCronTaskUid: job.taskUid, cronExpression: input.cronExpression, isEnabled: true }).where(eq(automationJobs.id, existing.id));\n      else await db.insert(automationJobs).values({ userId: ctx.user.id, name: `flowpromos-scan-${ctx.user.id}`, scheduleCronTaskUid: job.taskUid, cronExpression: input.cronExpression, isEnabled: true });\n      return { success: true, taskUid: job.taskUid };\n    }),\n    disable: protectedProcedure.mutation(async ({ ctx }) => {\n      const db = await getDb();\n      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });\n      const [job] = await db.select().from(automationJobs).where(eq(automationJobs.userId, ctx.user.id)).limit(1);\n      if (!job?.scheduleCronTaskUid) return { success: true };\n      const session = parseCookie(ctx.req.headers.cookie || "")[COOKIE_NAME] || "";\n      await deleteHeartbeatJob(job.scheduleCronTaskUid, session);\n      await db.update(automationJobs).set({ scheduleCronTaskUid: null, isEnabled: false }).where(eq(automationJobs.id, job.id));\n      return { success: true };\n    }),\n  }),\n'''
if marker not in s: raise SystemExit('marker missing')
p.write_text(s.replace(marker,module+marker,1))
PY
python3 /home/ubuntu/flowpromos/scripts/insert_automation_router.py
